Blog_base/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from gird_blog.views import home

urlpatterns = [
    url(r'^', include('gird_blog.urls')),
    url(r'^admin/', admin.site.urls),
    ##url(r'^', home, name='home'),
]

gird_blog/urls.py
"""
URL прилодения gird_blog
"""
from django.conf.urls import url
from gird_blog.views import home, newslenta, articles, contacts, projects, detail

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^news/$', newslenta, name='news'),
    url(r'^articles/$', articles, name='articles'),
    url(r'^articles/sort/(?P<tag_id>[0-9]+)/$', articles, name='articles_sort'),
    url(r'^articles/detail/(?P<article_id>[0-9]+)/$', detail, name='detail'),
    url(r'^contacts/$', contacts, name='contacts'),
    url(r'^projects/$', projects, name='projects'),
]

gird_blog/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class SiteInfo(models.Model):
    lable = models.CharField(max_length=100)
    title_text = RichTextField()

    def __str__(self):
        return self.lable

class Event(models.Model):
    time = models.DateTimeField()
    summary = RichTextField()

class Newslenta(models.Model):
    time = models.DateTimeField()
    place = models.CharField(max_length=200, blank=True)
    slug = models.SlugField()
    title = models.CharField(max_length=200)
    abstract = RichTextField()
    source = models.CharField(max_length=500)

    class Meta:
        ordering = ['-time']


class Article(models.Model):
    time = models.DateTimeField()
    title = models.CharField(max_length=200)
    abstract = RichTextField()
    content = RichTextField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-time']

class Keywords(models.Model):
    tag_word = models.CharField(max_length=30)
    article = models.ManyToManyField(Article)

    def __str__(self):
        return self.tag_word

gird_blog/views.py
from django.shortcuts import render,  get_object_or_404
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from gird_blog.models import SiteInfo, Newslenta, Event, Article, Keywords


# Create your views here.
def home(request):
    main_info = SiteInfo.objects.get(lable="О проекте")
    return render(request, 'index.html', {'main_info': main_info})

def newslenta(request):
    events = Event.objects.all().filter(time__gte=timezone.now())
    news_list = Newslenta.objects.all().filter(time__lte=timezone.now())
    paginator = Paginator(news_list, 20)
    page = request.GET.get('page')
    try:
        newslenta = paginator.page(page)
    except PageNotAnInteger:
        newslenta = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver last page of results.
        newslenta = paginator.page(paginator.num_pages)
    return render(request, 'news.html', {'newslenta': newslenta, 'events': events})

def articles(request, tag_id=None):
    if tag_id == None:
        articles_list = Article.objects.all()
    else:
        articles_list = Article.objects.filter(keywords__pk = tag_id)
    tags = Keywords.objects.all().order_by('tag_word')
    paginator = Paginator(articles_list, 5)
    page = request.GET.get('page')
    try:
        articleslenta = paginator.page(page)
    except PageNotAnInteger:
        articleslenta = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver last page of results.
        articleslenta = paginator.page(paginator.num_pages)
    return render(request, 'articles.html', {'articleslenta': articleslenta, 'tags': tags})

def detail(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    return render(request, 'detail.html', {'article': article})

def projects(request):
    return render(request, 'projects.html', {})

def contacts(request):
    contact_info = get_object_or_404(SiteInfo, lable="Контакты")
    return render(request, 'contacts.html', {'contact_info': contact_info})

gird_blog/templates/articles.html
{% extends 'base.html' %}
{% block content %}
<!-- container -->
<div class="container" xmlns="">
	<div class="row">	
		
		<!-- Sidebar -->
		<aside class="col-md-2 sidebar sidebar-left hidden-xs hidden-sm">
			<div class="row widget">
				<div class="col-xs-12">
					<p></p>
					<blockquote>
					<p>
					{% for tag in tags %}
                        <a href="/articles/sort/{{ tag.pk }}/">{{ tag.tag_word }}<br></a>
					{% endfor %}
					</p>
					</blockquote>
				</div>
			</div>
		</aside>
		<!-- /Sidebar -->

		<!-- Article main content -->
		<article class="col-md-10 maincontent">
			<header class="page-header">
				<h1 class="page-title">Статьи</h1>
			</header>
            {% for article in articleslenta %}
            <div class="container"> 
			<h2 class="nameart"><a href="/articles/detail/{{ article.pk }}/">{{ article.title }}</a></h2>
			<h5>{{ article.time }}</h5>
			<p class="article">{{ article.abstract|safe }}</p>
			<h5 class="tagart">
			{% for tag in article.keywords_set.all %}
			<a href="/articles/sort/{{ tag.pk }}/">
				{{ tag }};
			</a>
			{% endfor %}
			</h5>
			</div>
            {% endfor %}
        </article>		
		<!-- /Article -->
	</div>
</div><!-- /container -->
<nav>
    <ul class="pager">
        {% if articleslenta.has_previous %}
        <li><a href="?page={{ articleslenta.previous_page_number }}"> < </a></li>
        {% endif %}
        {% if articleslenta.has_next %}
        <li><a href="?page={{ articleslenta.next_page_number }}"> > </a></li>
        {% endif %}
    </ul>
 </nav>
{% endblock %}

gird_blog/templates/contacts.html
{%  extends 'base.html' %}
{%  load staticfiles %}
{%  block content %}
    <div class="container">
    <div class="row">
        <p></p>
    <img class ="info_img" src="{% static 'image/logo_big.png'%}">
    </div>
        </div>
	<div id="f">
		<div class="container">
			<div class="row">
				<h3>{{ contact_info.lable }}</h3>
				<p class="centered"><i class="icon icon-circle"></i><i class="icon icon-circle"></i><i class="icon icon-circle"></i></p>

				<div class="col-lg-6 col-lg-offset-3">
					<p>{{ contact_info.title_text|safe }}</p>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

gird_blog/templates/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div id="f">
		<div class="container">
			<div class="row">
				<h3>{{ article.title}}</h3>
				<p class="centered"><i class="icon icon-circle"></i><i class="icon icon-circle"></i><i class="icon icon-circle"></i></p>
				<!-- INTRO INFORMATIO-->
				<div class="justify col-lg-10 col-lg-offset-1" >
				<p>{{ article.content|safe }}</p>
				<h5 class="tagart">
				{% for tag in article.keywords_set.all %}
				<a href="/articles/sort/{{ tag.pk }}/">
					{{ tag }};
				</a>
				{% endfor %}
				</h5>
				</div>								
			</div>
		</div>
	</div>
{% endblock %}

gird_blog/templates/index.html
{% extends 'base.html' %}
{% block content %}
	<!-- ========== HEADER SECTION ========== -->
	<section id="home" name="home"></section>
	<div id="headerwrap">
		<div class="container">
			<div class="logo">
				<!-- <img src=""> -->
			</div>
			<br>
			<div class="row">
				<h1>"ВЕНЕРА"</h1>
				<br>
				<h3>ГИРД-2.0</h3>
				<br>
				<br>
				<div class="col-lg-6 col-lg-offset-3">
				</div>
			</div>
		</div><!-- /container -->
	</div><!-- /headerwrap -->
	
	
	<!-- ========== ABOUT SECTION ========== -->
	<section id="about" name="about"></section>
	<div id="f">
		<div class="container">
			<div class="row">
				<h3>{{ main_info.lable }}</h3>
				<p class="centered"><i class="icon icon-circle"></i><i class="icon icon-circle"></i><i class="icon icon-circle"></i></p>
				
				<!-- INTRO INFORMATIO-->
				<div class="col-lg-8 col-lg-offset-2">
					<p>{{ main_info.title_text|safe }}</p>
					<p></p>
				</div>								
			</div>
		</div><!-- /container -->
	</div><!-- /f -->
{% endblock %}

gird_blog/templates/news.html
{% extends 'base.html' %}
{% block content %}
<!-- container -->
<div class="container">
	<div class="row">		
		<!-- Sidebar -->
		<aside class="col-md-4 sidebar sidebar-left">
			<div class="row widget">
				<div class="col-xs-12">
					<p></p>
					<h4>Ближайшие мероприятия</h4>
                    {% if events %}
                        {% for event in events %}
                        <blockquote>
                            {{ event.time|date:"d E Y H:i" }}
                            {{ event.summary|safe }}
                        </blockquote>
                        {% endfor %}
                        {% else %}
                        <blockquote>
                        <p>Мероприятий на ближайшее время не запланировано.</p>
                        </blockquote>
                    {% endif %}
				</div>
			</div>
		</aside>
		<!-- /Sidebar -->

		<article class="col-md-8 maincontent">
			<header class="page-header">
				<h1 class="page-title">Новости</h1>
			</header>
            {% for news in newslenta %}
			<h2 class="nameart"><a href="{{ news.source }}">{{ news.title }}</a></h2>
			<h5>{{ news.time }}</h5>
			<p class="article">{{ news.abstract|safe }}</p>
            {% endfor %}
        </article>
	</div>
</div>	<!-- /container -->
<nav>
    <ul class="pager">
        {% if newslenta.has_previous %}
        <li><a href="?page={{ newslenta.previous_page_number }}"> < </a></li>
        {% endif %}
        {% if newslenta.has_next %}
        <li><a href="?page={{ newslenta.next_page_number }}"> > </a></li>
        {% endif %}
    </ul>
 </nav>
{% endblock %}

gird_blog/templates/projects.html
{%  extends 'base.html' %}
{%  load staticfiles %}
{%  block content %}
    <div class="container">
    <div class="row">
        <p></p>
    <img class ="info_img" src="{% static 'image/process.png'%}" height="200" width="150">
    </div>
    </div>
	<div id="f">
		<div class="container">
			<div class="row">
				<h3>Страница находится в разработке...</h3>
			</div>
		</div>
	</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="apple-touch-icon" sizes="57x57" href="{%  static 'image/favicon_set/apple-icon-57x57.png' %}">
  <link rel="apple-touch-icon" sizes="60x60" href="{%  static 'image/favicon_set/apple-icon-60x60.png' %}">
  <link rel="apple-touch-icon" sizes="72x72" href="{%  static 'image/favicon_set/apple-icon-72x72.png' %}">
  <link rel="apple-touch-icon" sizes="76x76" href="{%  static 'image/favicon_set/apple-icon-76x76.png' %}">
  <link rel="apple-touch-icon" sizes="114x114" href="{%  static 'image/favicon_set/apple-icon-114x114.png' %}">
  <link rel="apple-touch-icon" sizes="120x120" href="{%  static 'image/favicon_set/apple-icon-120x120.png' %}">
  <link rel="apple-touch-icon" sizes="144x144" href="{%  static 'image/favicon_set/apple-icon-144x144.png' %}">
  <link rel="apple-touch-icon" sizes="152x152" href="{%  static 'image/favicon_set/apple-icon-152x152.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{%  static 'image/favicon_set/apple-icon-180x180.png' %}">
  <link rel="icon" type="image/png" sizes="192x192"  href="{%  static 'image/favicon_set/android-icon-192x192.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{%  static 'image/favicon_set/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{%  static 'image/favicon_set/favicon-96x96.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{%  static 'image/favicon_set/favicon-16x16.png' %}">
  <link rel="manifest" href="{%  static 'image/favicon_set/manifest.json' %}">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="{%  static 'image/favicon_set/ms-icon-144x144.png' %}">
  <meta name="theme-color" content="#ffffff">
  
  <title>ВЕНЕРА ГИРД-2.0</title>
  
  <!-- Bootstrap core CSS -->
  <link href="{%  static 'css/bootstrap.css' %}" rel="stylesheet">
  
  <!-- Custom styles for this template -->
  <link href="{% static 'css/main.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{%  static 'css/font-awesome.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>

  
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='  stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet'  type='text/css'>
  
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="{%  static 'js/html5shiv.js' %}"></script>
    <script src="{%  static 'js/respond.min.js' %}"></script>
  <![endif]-->
</head>
<body data-spy="scroll" data-offset="0" data-target="#theMenu">
  
<!-- Menu -->
  <nav class="menu" id="theMenu">
    <div class="menu-wrap">
      <h1 class="logo"><a href="{% url 'home' %}">Главная</a></h1>
      <i class="icon-remove menu-close"></i>
      <a href="{% url 'news' %}">Новости</a>
      <a href="{% url 'articles' %}">Статьи</a>
      <a href="{% url 'projects' %}">Проекты</a>
      <a href="{% url 'contacts' %}">Контакты</a>
      <!-- Social
      <a href="#"><i class="icon-facebook"></i></a>
      <a href="#"><i class="icon-twitter"></i></a>
      <a href="#"><i class="icon-dribbble"></i></a>
      <a href="#"><i class="icon-envelope"></i></a>
      -->
    </div>
    
    <!-- Menu button -->
    <div id="menuToggle"><i class="icon-reorder"></i></div>
  </nav>

  {% block content %}
  {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  <script src="{% static 'js/classie.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/smoothscroll.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
    <script src='//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'></script>
</body>
</html>